### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by DamageMaximo** [Judgy53/WaterTweaker#2]
When entering Wetland Aspect the game heavily lags for around 5 seconds and the water's opacity is unchanged, most likely a new bug because of the new devotion update and the new stage verdant falls

**Comment by Judgy53** [comment]
Thanks for the report. I've fixed it in 6bdfaf3dd4ed59d38ce0aeb8c5acf4df375077fd and also reduced the lag that failure caused. 
Let me know if there's still an issue.

**Comment by DamageMaximo** [comment]
Thank you it's fixed now!
